### ISSUE TITLE
[3004.388.10] [Beta2] [TUF-AX5400] TUF UI Bug

### ISSUE THREAD

**Issue by cristobalo7** [gnuton/asuswrt-merlin.ng#882]
Thank you @gnuton for taking the time and effort.

3004.388.10 no issue with default UI.

**Router Model Affected**
TUF-AX5400

**Firmware Version Affected**
3004.388.10_0-gnuton0_beta1_tuf

**Bugs:**

- [ ] 1. Missing Menu: **DNS Director**
- [ ] 2. Missing Menu: **Tweaks**

- [ ] 2.4Ghz 5Ghz **Wireless settings page are broken**
(not saving settings, channels are not visible,
5Ghz -2 option which is not applicable to this model)

**Screenshots**

<img width="414" height="114" alt="Image" src="https://github.com/user-attachments/assets/f9273617-bdae-4296-b39c-9564628558f2" />

<img width="595" height="101" alt="Image" src="https://github.com/user-attachments/assets/1c55e1c0-3e3d-4703-9e1e-459e241bba45" />

<img width="567" height="712" alt="Image" src="https://github.com/user-attachments/assets/4b890fd6-6a59-4e4e-8a21-8a104d079bcb" />

<img width="595" height="1086" alt="Image" src="https://github.com/user-attachments/assets/0efe757c-dba4-4b36-9c1e-4139897bdbf9" />

**Comment by gnuton** [comment]
Hi,
can you please tell me which errors do you see in the console hen you apply the settings in the wireless page?

**Comment by cristobalo7** [comment]
> Hi, can you please tell me which errors do you see in the console hen you apply the settings in the wireless page?

Hi.

**Wireless page errors from console**:

<img width="851" height="211" alt="Image" src="https://github.com/user-attachments/assets/3839ecbc-bba9-4e0b-8c14-fc1c2950ca7b" />

**Comment by cristobalo7** [comment]
**3004.388.10_2-gnuton0_beta2_tuf**

Missing menu and broken WIreless settings page
still present in beta 2.

<img width="567" height="902" alt="Image" src="https://github.com/user-attachments/assets/e03a3ec5-848b-44c5-8a65-cbfd547992ef" />
<img width="567" height="787" alt="Image" src="https://github.com/user-attachments/assets/7f5ea948-6999-4af8-9624-525517251d41" />
<img width="425" height="93" alt="Image" src="https://github.com/user-attachments/assets/529a1410-8a01-4ebf-a41c-e5336cba7815" />

**Comment by gnuton** [comment]
Thanks for reporting this will be fixed before the release goes out.
I think I got were the problem is.. I need to find a way to fix it. 
Cheers

**Comment by cristobalo7** [comment]
> Thanks for reporting this will be fixed before the release goes out. I think I got were the problem is.. I need to find a way to fix it. Cheers

Thank you. Appreciate it. 👍🏻

**Comment by qqw1231** [comment]
> > 感谢您的报告，这将在发布之前得到修复。我想我明白了问题是......我需要找到一种方法来解决这个问题。干杯
> 
> 谢谢。欣赏它。👍🏻

Are you logging in from a mobile phone or a computer?

**Comment by Marchcat2008** [comment]
> > > 感谢您的报告，这将在发布之前得到修复。我想我明白了问题是......我需要找到一种方法来解决这个问题。干杯
> > 
> > 
> > 谢谢。欣赏它。👍🏻
> 
> Are you logging in from a mobile phone or a computer?

This error occurs both when logging in from a computer and when logging in from a mobile phone.

**Comment by jmcmillan45-cloud** [comment]
There is the exact same issues as the OP's on the TUF-AX3000V2 .

**Comment by gnuton** [comment]
@cristobalo7 https://github.com/gnuton/asuswrt-merlin.ng/actions/runs/19362327856  test images here.
All three issues should be fixed. 
Please test them if you have time and report.

**Comment by cristobalo7** [comment]
> [@cristobalo7](https://github.com/cristobalo7) https://github.com/gnuton/asuswrt-merlin.ng/actions/runs/19362327856 test images here. All three issues should be fixed. Please test them if you have time and report.

Hi, bug fix confirmed.
Thank you. ❤️👍🏻

**DNS Director**
<img width="425" height="402" alt="Image" src="https://github.com/user-attachments/assets/0ee29c6c-7fbd-4050-955d-da5ebfd94cbc" />

**Tweaks**
<img width="425" height="500" alt="Image" src="https://github.com/user-attachments/assets/9d68b231-07bc-486c-b16d-50b28f000660" />

**5Ghz**
<img width="319" height="133" alt="Image" src="https://github.com/user-attachments/assets/f86d592c-55b6-443e-a2cc-4203828c8b23" />

**Wireless Settings**
<img width="425" height="470" alt="Image" src="https://github.com/user-attachments/assets/c57b10c1-e093-495a-b74f-801578817645" />

**Comment by qqw1231** [comment]
> > [@cristobalo7 https://github.com/gnuton/asuswrt-merlin.ng/actions/runs/19362327856](https://github.com/cristobalo7)  测试图像 点击此处.这三个问题都应该得到解决。如果您有时间并报告，请测试它们。
> 
> 嗨，错误修复已确认。 谢谢。❤️👍🏻
> 
> **DNS 总监** <img alt="图像" width="425" height="402" src="https://private-user-images.githubusercontent.com/141552727/514417695-0ee29c6c-7fbd-4050-955d-da5ebfd94cbc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMxMjU3MjQsIm5iZiI6MTc2MzEyNTQyNCwicGF0aCI6Ii8xNDE1NTI3MjcvNTE0NDE3Njk1LTBlZTI5YzZjLTdmYmQtNDA1MC05NTVkLWRhNWViZmQ5NGNiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExNFQxMzAzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDVlNDdkM2M2YmRhNzA1YzM1MzFhNmY2YzNlYzIyNGIyOTQzNTkyOGVhYTJmODUxZGM1OWZiYjJlOTNlODQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BPtUPTqR0ATzBeUymtk5SOxoD_symyKpIVOvyYORwj4">
> 
> **调整** <img alt="图像" width="425" height="500" src="https://private-user-images.githubusercontent.com/141552727/514417693-9d68b231-07bc-486c-b16d-50b28f000660.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMxMjU3MjQsIm5iZiI6MTc2MzEyNTQyNCwicGF0aCI6Ii8xNDE1NTI3MjcvNTE0NDE3NjkzLTlkNjhiMjMxLTA3YmMtNDg2Yy1iMTZkLTUwYjI4ZjAwMDY2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExNFQxMzAzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGI2YTY2ZDRiNDIwNGE0Y2M5MTRiZDBiZjI3NTlmM2ZiMTU5NjNjOTRmMzBlODczZTBlYWE2NmE2MTdiNmNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aTPVAxfvioJOGa1NM5OHqtBNXTOwIlUQrmthb47_5L0">
> 
> **5兆赫兹** <img alt="图像" width="319" height="133" src="https://private-user-images.githubusercontent.com/141552727/514419045-f86d592c-55b6-443e-a2cc-4203828c8b23.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMxMjU3MjQsIm5iZiI6MTc2MzEyNTQyNCwicGF0aCI6Ii8xNDE1NTI3MjcvNTE0NDE5MDQ1LWY4NmQ1OTJjLTU1YjYtNDQzZS1hMmNjLTQyMDM4MjhjOGIyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExNFQxMzAzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDMxZjAwYThlNzRjNjY1YTJkZmY5MjdlOWMwNDc1NGYyOTk5OGZmMDA4ODk2ZDJmZmQ1YzNiZDdhZWViZjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hWzfRai9qaC7tPFJ996VcUuFeHT6CFr0By4liafNegs">
> 
> **无线设置** <img alt="图像" width="425" height="470" src="https://private-user-images.githubusercontent.com/141552727/514417696-c57b10c1-e093-495a-b74f-801578817645.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMxMjU3MjQsIm5iZiI6MTc2MzEyNTQyNCwicGF0aCI6Ii8xNDE1NTI3MjcvNTE0NDE3Njk2LWM1N2IxMGMxLWUwOTMtNDk1YS1iNzRmLTgwMTU3ODgxNzY0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExNFQxMzAzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTBkYTEzM2I1NWVmNzU1ZDViZDBhODc5Zjk2NGNhYjE2MDNhNWEwOGY2YTE2YTExNjRkYzBjNTZiZWY4MWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G4FKDS9RPn9YvxA8-w7X3fBrRVFecZKuanlARwJrdwI">

Is your head and mid-lower part tilted when you log in with your mobile phone? UI

**Comment by cristobalo7** [comment]
> Is your head and mid-lower part tilted when you log in with your mobile phone? UI

Hi, logged-in view via mobile browser.

<img width="273" height="567" alt="Image" src="https://github.com/user-attachments/assets/394d9d81-829e-4f16-86f6-074ac8605719" />

<img width="271" height="567" alt="Image" src="https://github.com/user-attachments/assets/a6f39e77-5e94-45c3-a846-1f5d9e86fbdb" />

**Comment by qqw1231** [comment]
> > Is your head and mid-lower part tilted when you log in with your mobile phone? UI
> 
> Hi, logged-in view via mobile browser.
> 
> <img alt="Image" width="273" height="567" src="https://private-user-images.githubusercontent.com/141552727/514505864-394d9d81-829e-4f16-86f6-074ac8605719.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMxNDQzMzksIm5iZiI6MTc2MzE0NDAzOSwicGF0aCI6Ii8xNDE1NTI3MjcvNTE0NTA1ODY0LTM5NGQ5ZDgxLTgyOWUtNGYxNi04NmY2LTA3NGFjODYwNTcxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExNFQxODEzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTQ0NDcyMzY4MTE2ZGRhMWNlOTVhNGU3YjA2MWU1OTcwMzA1OGVkZTFkMWIyOWZlMzk3MGUwMjBhMTIzN2Q5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.e4Lq6wx9T29Ts-dEtTL4exzK5Gr8MwXAG9HSTN00IOY"> <img alt="Image" width="271" height="567" src="https://private-user-images.githubusercontent.com/141552727/514506739-a6f39e77-5e94-45c3-a846-1f5d9e86fbdb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMxNDQzMzksIm5iZiI6MTc2MzE0NDAzOSwicGF0aCI6Ii8xNDE1NTI3MjcvNTE0NTA2NzM5LWE2ZjM5ZTc3LTVlOTQtNDVjMy1hODQ2LTFmNWQ5ZTg2ZmJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExNFQxODEzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2M0ZThmYWMwZWY5ZmJjOTExZmI0Yjg4YmE4M2FjYzUyNDkyZDI4Y2JiZTU4ODFiMTBkYmRkNTkyY2U0ZWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3m36fzr5QEx-quBV5r-aUaI7lNSztnDKjtSMSYx7DOA">

The UI is still not fixed, and there are compatibility issues at the top and middle of the screen.

**Comment by gnuton** [comment]
Changes will be part of the next release
